base_url = "https://iamdejan.my.id"

title = "Giovanni Dejan"

build_search_index = false

theme = "kodama-theme"

[markdown]
highlight_code = true

[extra]

avatar = "static/img/avatar.jpg"
favicon = "static/img/avatar.jpg"

contact_in_index = false

menu_items = [
]
